In [1]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
test_images.shape

(10000, 28, 28)

In [5]:
len(test_labels)

10000

In [6]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(521, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

In [9]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [10]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 8s 133us/step - loss: 0.2545 - acc: 0.9264 0s - loss: 0.269
Epoch 2/5
60000/60000 [==============================] - 8s 128us/step - loss: 0.1027 - acc: 0.9702 3s - loss: 0.1100 - a - ETA: 0s - loss: 0.1032 - acc: 0.97
Epoch 3/5
60000/60000 [==============================] - 10s 162us/step - loss: 0.0683 - acc: 0.9793
Epoch 4/5
60000/60000 [==============================] - 9s 142us/step - loss: 0.0499 - acc: 0.9847
Epoch 5/5
60000/60000 [==============================] - 10s 165us/step - loss: 0.0364 - acc: 0.98953s - loss: 0.0367


In [11]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 131us/step
test_acc: 0.9798


In [12]:
# Scalars (0D tensors)

import numpy as np

x = np.array(12)
print(x)
print(x.ndim)

12
0


In [13]:
# Vectors (1D tensors)
x = np.array([12, 3, 6, 14])
print(x)
print(x.ndim)

[12  3  6 14]
1


In [14]:
# Matrices (2D tensors)
x = np.array([[5, 78, 2, 34, 0], 
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]])
print(x.ndim)

2


In [15]:
# 3D tensors
x = np.array([[[5, 78, 2, 34, 0], 
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0], 
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0], 
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]]])
print(x.ndim)

3


In [16]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [17]:
print(train_images.ndim)

3


In [18]:
print(train_images.shape)

(60000, 28, 28)


In [19]:
print(train_images.dtype)

uint8


In [20]:
digit = train_images[4]

import matplotlib.pyplot as plt
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

In [21]:
my_slice = train_images[10:100]
print(my_slice.shape)

(90, 28, 28)


In [22]:
my_slice = train_images[10:100, :, :]
print(my_slice.shape)

(90, 28, 28)


In [23]:
my_slice = train_images[10:100, 0:28, 0:28]
print(my_slice.shape)

(90, 28, 28)


In [24]:
my_slice = train_images[:, 14:, 14:]
print(my_slice.shape)
my_slice = train_images[:,7:-7, 7:-7]
print(my_slice.shape)

(60000, 14, 14)
(60000, 14, 14)


In [25]:
batch = train_images[:128]
print(batch.shape)
batch = train_images[128:256]
print(batch.shape)

n = 10
batch = train_images[128 * n:128 * (n + 1)]
print(batch.shape)

(128, 28, 28)
(128, 28, 28)
(128, 28, 28)


In [26]:
# this function is a naive implementation of an element-wise relu operation
def naive_relu(x):
    # Make sure that x is 2D-tensor
    assert len(x.shape) == 2
    # Avoid overwrite the input tensor
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [27]:
# this function is a naive implementation of an element-wise add operation
def naive_add(x, y):
    # Make sure that x and y are 2D-tensor
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    # Avoid overwrite the input tensor
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [28]:
import numpy as np

x = np.random.rand(3, 3)
y = np.random.rand(3, 3)

z = x + y
print(z)
z = np.maximum(z, 0.)
print(z)

[[0.86796278 1.75343164 1.62326076]
 [1.17557791 1.21262917 0.07256743]
 [1.073105   1.35621318 1.27286873]]
[[0.86796278 1.75343164 1.62326076]
 [1.17557791 1.21262917 0.07256743]
 [1.073105   1.35621318 1.27286873]]


In [29]:
# this function is a naive implementation add operation between a matrix and a vector
def naive_add_matrix_and_vector(x, y):
    # Make sure that x is 2D-tensor
    assert len(x.shape) == 2
    # Make sure that y is 1D-tensor
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    # Avoid overwrite the input tensor
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [30]:
import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))

z = np.maximum(x, y)
print(z.shape)

(64, 3, 32, 10)


In [31]:
import numpy as np

x = np.random.rand(3, 3)
y = np.random.rand(3, 3)

z = np.dot(x, y)
print(z)

[[0.76419512 1.0993422  0.46631601]
 [0.55376982 0.81238432 0.76014933]
 [0.56602528 0.47972273 0.64756445]]


In [32]:
# this function is a naive implementation vectors dot product
def naive_vector_dot(x, y):
    # Make sure that x and y are 1D-tensor
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [33]:
import numpy as np

# this function is a naive implementation matrix and vector dot product
def naive_matrix_vector_dot(x, y):
    # Make sure that x is 2D-tensor
    assert len(x.shape) == 2
    # Make sure that y is 1D-tensor
    assert len(y.shape) == 1
    # The first dimension of x must be the same as the 0th dimension of y
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [35]:
def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z


In [36]:
# this function is a naive implementation of matrices dot product
def naive_matrix_dot(x, y):
    # Make sure that x and y are 2D-tensor
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    # The first dimension of x must be the same as the 0th dimension of y
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

In [37]:
x = np.array([[0., 1.],
            [2., 3.],
            [4., 5.]])

print(x.shape)

(3, 2)


In [38]:
x = x.reshape((6, 1))
print(x.shape)

x = x.reshape((2, 3))
print(x.shape)


(6, 1)
(2, 3)


In [39]:
x = np.zeros((300, 20))
x = np.transpose(x)
print(x.shape)

(20, 300)
